server:
  port: 60080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: DanceGrade
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/test?user=user0&password=A1145141919810a_"

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: "org.apache.ibatis.logging.stdout.StdOutImpl"
