CREATE TABLE danceData (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
  studentId BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  actions VARCHAR(255) NOT NULL,
  scores VARCHAR(255) NOT NULL,
  scoreAvg DOUBLE NOT NULL
)
